sudo: required
dist: bionic

env:
  matrix:
    - NAME=bc-raspbian-buster-lite
      URL=https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-09-30/2019-09-26-raspbian-buster-lite.zip
      SHA256=a50237c2f718bd8d806b96df5b9d2174ce8b789eda1f03434ed2213bbca6c6ff

    - NAME=bc-raspbian-buster
      URL=https://downloads.raspberrypi.org/raspbian/images/raspbian-2019-09-30/2019-09-26-raspbian-buster.zip
      SHA256=2c4067d59acf891b7aa1683cb1918da78d76d2552c02749148d175fa7f766842

env:
  global:
    # GITHUB_TOKEN
    - secure: nEA4ZTu7geyQ3OSrNWz8NQIutMz5owhYrAoIVeHbjM/jQes4szIdPGDKpgj3YSO1F6G7UOG8JMkLPLcaBlK5uNXBpv3sQhxv2pXai+rz9ZqK3CBiefII4gl1hdlnJIDVrvpXOmvKsMK8zSBmKWBJJDjTsNSsuHym9P6FjuE76H6jFbTiEX4VVHCiohoId9jTJEYUf6eEmXi/iz9fH/IRNTiQQhvwsdTqcs/mtleTyadt8K0tMoxLw9fyUsP0UDVZNZNIDo6yAX4pULXNV0ET9RAqHk6ysGBfjiH6JAcqV6rxFLE5By5mUxxksQeKYI/DIrdk5wt3g+8G/5iFkGH92UEb0EYv2lEkeinAzBFMOK/ayWxvlnmzXbapz7saN+EbwmkNCmFkpGfuY66OEN/e2Uc3PTa1GfH2SVtO+5K7+yQ8IW9I3Ky9x1+QzHpYw2MEDfejzMnDzc4SJXZIkX+9oOX8Jtm/6KUrYcjXqYCoUtWGhQKhgbg763uVtQuEJ3N4s9Zd0K1VZReqPkFTBlopDyF9saSoeK6ZVGWp8AME7kY3ADMnSVgLpIptlGZ5Fzy3y1xiZ/BWGwWjg1owAL1otOgw21IY+HeteL6ubhC47KJN8DJDhaL0MrBN6uuS27FMK3EBUkYOp4j8gqX2ubRtGvNuZSTXJkb1Go6z4LShApw=

    # SLACK_TOKEN
    - secure: NNh0Cgeba0OZuPyWzsoR3W2Sa1ha/YPYhCsnAXaSqtnLE5BNYtqWZUapCKRfvRHomjj0QTLUeJA8WLPP899N/WFld4rK5T2uE0Rny0OpGlPWw2hsWbS/U+wbt8CgwA3zYqK36ap+/3IbcEwjUBREoOlx/UUFaRly73PYJFHbOO29vrqT0/WxepnJwCG0A70G84DE0eQqxjf87qMqk7EffJ3KVyvKXDYjgzMq24TrAKkS3VqKFYnHFzXPbzUdsYhFCCYDWDyiBnZSlnWofhjmiNcfzP7Bscyy+DVXAkzz5pPCkcQutMPM1DC3g8fIKcW6oKKW8Bu8zaBLOsynZXj4FbK0KZUdjr/wFpjTiUJaSp3aCqeCwXT/7pKZm9X8+hDeISS+mMfH2p+cuhAA/pAyUk9kQxBNknoI2vLZAEjby7KAddxchZIbu1diqOENQ8s9/LLbSZ/GyWhlWgZ8Hdy79gb75y19nCHHP87YtrkO01R7ZI6dPH75HVZDiVRo84SMwf2grucDUsliSU+5j27WnmbjHJFLSFIzURgNiVMbjJcBbZdfcXITP8rD8PkSoL+BsYVMU3Y6bhZxxhv0zgA+irXos7paPzMbxoiBsxq256tp5Gb0YuIALtQNZ/VgC5yxKREhAWQ5vXAuV1lvYTb5YH+9bli0ch7KXfkBsrqIGgg=

addons:
  apt:
    packages:
    - kpartx
    - coreutils
    - qemu-user-static
    - zip
    - unzip
    - binfmt-support
    - openssl

script:
  - hostname
  # - sudo ./build.sh

before_deploy:
  # Workaround for https://github.com/travis-ci/dpl/issues/542
  - sudo chown $(id -u) *.zip

deploy:
  provider: releases
  api_key: ${GITHUB_KEY}
  file: "bc-raspbian-*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

after_script:
  - cd _util
  - id
  - sudo apt update
  - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  - pip3 install --user pipenv
  - pipenv sync
  - pipenv run python3 merge.py

notifications:
  slack:
    secure: RZ4elvQL+BmBgC1ITAvamgZ1zrlLrA/iXZ5tYYi6PbOBEqJXeD0ATz4MyGf3OvOrlV1jwFd4Cm0CnYbLQOb5fj2XvdBelay6hdwnglKAO7yf0GL09l0ZVQrSTExb3DLjWvkGURvnJxPkGwXqGCe7qnDpUEWcH+4O7mVZdQtICJqlhlQw3Def5NgZupHKuGYM8YblWNgDlKObrNbbHmDyaaOO8GGKkZ/oYFhVw1DmtNXfqaUuCxxjLNUlPMVEVw/QGoyuGhTbaSKdfGO53n7wX7u9bMRJ9EnbjQuJPp/wRfCPfyNx2dbSSkdGOeUbW+LbRgxqdPbhIoP6ys2L+bhMxpH1EZNdmuEf7SVyN+XA8IUQUphBKoHdYIzRy8XNYStXKElA5TIYmQpa458c+zyuq+A2Ugu/RHhi+Hi0W9vAMq4+KCoeHjIGy8kdJPpUt11KeryPEO5gwKPpV5h2ru7X14kqwa5keW4o9+bhvSau8849MOXUo8n9/qh/zEtuc4KdypNThib7f4LBivtWw3Lw3nrhCqHCqSJlxF5uky+Wr3/boEOLrG8/12rFNMaB0bv6lyqjDYRuv7R0zK7kSoLkN6q9zeu3QknBxkAAgFwag5PmkeIytwqW0VVWrnR7i7TYQqAnB2rJHzvYJtUj3vSold6nwfhk9AZyXqSsfoWZ4Sk=
